# Generated by Django 5.2.1 on 2025-05-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('marketer', 'Marketer'), ('influencer', 'Influencer')], max_length=20),
        ),
    ]
