# Generated by Django 5.2.1 on 2025-05-21 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Domicile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('categories', models.ManyToManyField(related_name='influencers', to='influencers.category')),
                ('domicile', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='influencers.domicile')),
            ],
        ),
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('profile_url', models.URLField()),
                ('username', models.CharField(max_length=100)),
                ('followers', models.PositiveIntegerField()),
                ('engagement_rate', models.CharField(blank=True, max_length=10, null=True)),
                ('avg_likes_per_post', models.CharField(blank=True, max_length=10, null=True)),
                ('avg_comments_per_post', models.CharField(blank=True, max_length=10, null=True)),
                ('avg_views_per_post', models.CharField(blank=True, max_length=10, null=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_platforms', to='influencers.influencer')),
            ],
        ),
    ]
