# Generated by Django 5.2.1 on 2025-05-22 16:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0002_influencer_profile_picture_alter_influencer_domicile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='id',
            field=models.CharField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
