# Generated by Django 5.2.1 on 2025-05-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0004_alter_category_id_alter_domicile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialplatform',
            name='profile_url',
            field=models.CharField(max_length=255),
        ),
    ]
