# Generated by Django 5.2.1 on 2025-05-23 00:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0005_alter_socialplatform_profile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialplatform',
            name='id',
            field=models.CharField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
