# Generated by Django 5.2.1 on 2025-05-23 15:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0007_alter_category_id_alter_domicile_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('social_platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_cards', to='influencers.socialplatform')),
            ],
        ),
    ]
