# Generated by Django 5.2.1 on 2025-05-22 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('influencers', '0002_influencer_profile_picture_alter_influencer_domicile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_goal', models.CharField(max_length=255)),
                ('campaign_budget', models.CharField(max_length=100)),
                ('campaign_timeline', models.CharField(max_length=100)),
                ('target_socialmedia', models.CharField(choices=[('yt', 'YouTube'), ('x', 'X'), ('ig', 'Instagram'), ('tiktok', 'TikTok')], max_length=10)),
                ('prefer_sosmed', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('umur', models.CharField(max_length=50)),
                ('category_product', models.CharField(max_length=100)),
                ('description_product', models.TextField()),
                ('target_interesting', models.ManyToManyField(related_name='campaigns', to='influencers.category')),
                ('target_location', models.ManyToManyField(related_name='campaigns', to='influencers.domicile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
