# Generated by Django 5.2.1 on 2025-05-23 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='target_interesting',
            new_name='target_interests',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='target_location',
            new_name='target_locations',
        ),
    ]
