# Generated by Django 5.2.1 on 2025-05-23 14:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_alter_campaign_id'),
        ('influencers', '0007_alter_category_id_alter_domicile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='recommended_influencers',
            field=models.ManyToManyField(blank=True, related_name='recommended_for', to='influencers.influencer'),
        ),
        migrations.CreateModel(
            name='MatchingReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='influencers.influencer')),
            ],
            options={
                'unique_together': {('campaign', 'influencer')},
            },
        ),
    ]
