# Generated by Django 5.2.1 on 2025-05-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_rename_campaign_budget_campaign_budget_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
